#Change to MySQL for mysql support#
#Change to SQLite for sqlite support#
Database: SQLite
#MySQL Information#
MySQL:
  Database: 'jdbc:mysql://localhost:3306/minecraft'
  User: 'root'
  Password: 'root'
  Table: 'banlist'
  IPTable: 'banlistip'
#SQLite Information#
SQLite:
  Filename: 'banlist'
#delete dat on ban#
CleanOnBan: true
#clear warnings on ban#
ClearWarnOnBan: false
#store unbans#
UnbansLog:
  Enable: true
  LogReason: true
#Max Warnings#
MaxWarning:
  Enable: false
  Amt: 5
  #ban,kick,ipban,perma,tempban,tempipban#
  Result: ban
  Silent: true
  Reason: 'Max Warnings'
  #Used with Temporary actions#
  Temp:
    Amt: 5
  #sec,min,hour,day,week,month#
    Mode: day
#Default labels#
Label:
  Console: 'Server'
  Reason: 'Unsure'
Login:
#Check for duplicates on Login#
  DupeCheck:
    Enable: true
#Check ping on Login#
  PingCheck:
    Enable: true
    MaxPing: 500
#PingBack joining players, and kick if unreachable. //Experimental#
  ProxyPingBack:
    Enable: false
    #How long in milliseconds to Timeout#
    Timeout: 10000
#This will set the server to sync the database if multiple servers are in place.#
Sync:
  Enabled: false
  #Timing is in Long format Example:#
  #1 Hour = 60 Seconds * 60 Minutes * 20 ServerTickRatePerSec = 72000L
  Timing: 72000L
#Auto Updater#
AutoUpdater:
  Enabled: true
#Error / Usage Tracking#
GoogleAnalytics:
  Enable: true
Messages:
  Ban:
    MsgToVictim: '&6You have been banned by &7%admin%&6. Reason: &7%reason%&6!'
    MsgToBroadcast: '&7%victim%&6 was banned by &7%admin%&6. Reason: &7%reason%&6!'
    Failed: '&4%victim%&c is already in banned.'
    Denied: '&cYour ban attempt has been denied!'
    Emo: '&cYou cannot ban yourself!'
    Login: '&7%admin%&6 banned you from this server! Reason: &7%reason%&6!'
  CheckBan:
    Header: '&6Found &7%amt%&6 records for &7%victim%&6.'
    None: '&cNo records found for &4%victim%&c.'
  DupeIP:
    Failed: '&cUnable to view ip for &4%victim% &c!'
    Header: '&6Scanning Current IP of &7%victim%&6: &7%ip% !'
    Completed: '&aScanning Complete!'
  Export:
    Failed: '&cCould not export ban lists.'
    Completed: '&aExported banlists.'
  History:
    Header: '&6Ultrabans Listing &7%amt%&6 Records.'
    Failed: '&cUnable to find any bans.'
  Import:
    Loading: '&cBe patient. Loading...'
    Failed: '&cCould not import ban list.'
    Completed: '&aSystem imported the banlist to the database.'
  IPBan:
    MsgToVictim: '&6You have been ipbanned by &7%admin%&6. Reason: &7%reason%&6!'
    MsgToBroadcast: '&7%victim%&6 was ipbanned by &7%admin%&6. Reason: &7%reason%&6!'
    IPNotFound: '&cIP address not found. &6Processed as a normal ban for &7%victim%&6!'
    Failed: '&4%victim%&c is already in banned.'
    Denied: '&cYour ipban attempt has been denied!'
    Emo: '&cYou cannot ipban yourself!'
    Login: '&7Your IP is banned!'
  Kick:
    MsgToAll: '&6Everyone has been kicked by &7%admin%&6. Reason: &7%reason%&6!'
    MsgToVictim: '&6You have been kicked by &7%admin%&6. Reason: &7%reason%&6!'
    MsgToBroadcast: '&7%victim%&6 was kicked by &7%admin%&6. Reason: &7%reason%&6!'
    Online: '&4%victim%&c must be online.'
    Denied: '&cYour kick has been denied!'
    Emo: '&cYou cannot kick yourself!'
  PermaBan:
    MsgToVictim: '&6You have been permabanned by &7%admin%&6. Reason: &7%reason%&6!'
    MsgToBroadcast: '&7%victim%&6 was permabanned by &7%admin%&6. Reason: &7%reason%&6!'
    Failed: '&4%victim%&c is already banned.'
    Online: '&4%victim%&c must be online.'
    Denied: '&cYour permaban has been denied!'
    Emo: '&cYou cannot permaban yourself!'
  TempBan:
    MsgToVictim: '&6You have been tempbanned by &7%admin%&6 for &7%amt% %mode%s.&6 Reason: &7%reason%&6!'
    MsgToBroadcast: '&7%victim%&6 was tempbanned by &7%admin%&6 for &7%amt% %mode%s.&6 Reason: &7%reason%&6!'
    Failed: '&4%victim%&c is already tempbanned!'
    Denied: '&cYour tempban has been denied!'
    Emo: '&cYou cannot tempban yourself!'
    Login: '&6You have been tempbanned by &7%admin%&6 for &7%time%&6. Reason: &7%reason%&6!'
  TempIpBan:
    MsgToVictim: '&6You have been tempipbanned by &7%admin%&6 for &7%amt% %mode%s.&6 Reason: &7%reason%&6!'
    MsgToBroadcast: '&7%victim%&6 was tempipbanned by &7%admin%&6 for &7%amt% %mode%s.&6 Reason: &7%reason%&6!'
    Failed: '&4%victim%&c is already tempipbanned!'
    Denied: '&cYour tempipban has been denied!'
    Emo: '&cYou cannot tempipban yourself!'
    IPNotFound: '&cIP address not found.&6 Processed as a normal tempban for &7%victim%&6!'
  Unban:
    MsgToBroadcast: '&7%victim%&6 was unbanned by &7%admin%&6!'
    PermaBanned: '&cUnable to unban, &7%victim%&c was Permabanned.'
    Failed: '&4%victim%&c is already unbanned!'
  Warn:
    MsgToVictim: '&6You have been warned by &7%admin%&6. Reason: &7%reason%&6!'
    MsgToBroadcast: '&7%victim%&6 was warned by &7%admin%&6. Reason: &7%reason%&6!'
    Denied: '&cYour warning has been denied!'
    Emo: '&cYou cannot warn yourself!'
  MaxWarn:
    MsgToBroadcast: '&7%cmd%&6 performed by Ultrabans on &7%victim%&6. Reason: &7Reached Max Warnings&6!'
  Permission: 'You do not have the required permissions.'
